### ISSUE TITLE
(Standard) Feil kardinalitet på forholdTilKilde

### ISSUE THREAD

**Issue by stigbd** [difi/forvaltningsstandard-begrep#3]
I https://doc.difi.no/data/forvaltningsstandard-begrepsbeskrivelser/#kildebeskrivelseA er kardinaliteten til forholdTilKilde oppgitt som 0..1. Denne burde være 1 (1:1), sidan Kildebeskrivelse alltid må ha en verdi for forholdTilKilde.

**Comment by jimjyang** [comment]
**Konklusjon** ifm. "årshjul 2019/2020": Kardinaliteten endres ikke denne gangen, siden det kan ha konsekvens for de som allerede har mange begrepsbeskrivelser. Vurderes ved neste større revisjon (som krever høring).

**Comment by jimjyang** [comment]
Tatt hensyn til i den reviderte versjonen.
