### ISSUE TITLE
[publisering] PDF-filnavnet bør gjenspeile spesifikasjonens navn

### ISSUE THREAD

**Issue by jimjyang** [difi/forvaltningsstandard-begrep#84]
Navnet til PDF-filen som kan lastes ned er nå "document.pdf". 

Ønsker å ha et filnavn som gjenspeile spesifikasjonens navn, f.eks. repo-navnet (som også brukes i URLen til den gjeldende versjonen på data.norge.no).

**Comment by stigbd** [comment]
Fiksa i efd477f79d5c194dd0adcf0f7fcaf89acfa08b11

**Comment by jimjyang** [comment]
Fiksa
