### ISSUE TITLE
(Standard) Behov for relasjonene skos:closeMatch og skos:exactMatch

### ISSUE THREAD

**Issue by synnesol** [difi/forvaltningsstandard-begrep#86]
I forbindelse med Nordic Smart Goverment & Business (NSGM), skal det lages en tjeneste for deling av foretaksinformasjon på tvers av de nordiske landene.
Vi er i ferd med å lage et felles begrepsapparat og en datamodell for dette (som gjøres i finnenes løsning, som vi har fått demonstrert en gang da jeg jobbet i Digdir).

Vi har imidlertid behov for å mappe våre nasjonale begreper mot fellesbegrepene i NSGM. Det er tenkt å bruke skos:closeMatch og skos:exactMatch til dette. Vi skulle gjerne ha hatt muligheten til å legge på slike relasjoner i Felles begrepskatalog.

**Comment by jimjyang** [comment]
Tatt med i revidert versjon.
